version: "3"

services:

  smcql_site1:
    platform: linux/amd64
    container_name: smcql_site1
    image: smcql_remote
    networks:
      smcql_bridge:
        ipv4_address: 172.123.0.11
    volumes:
      - ../sample-conf/remote/site1:/home/smcql/sample-conf
    restart: unless-stopped
    command: sleep infinity
    
  smcql_site2:
    platform: linux/amd64
    container_name: smcql_site2
    image: smcql_remote
    networks:
      smcql_bridge:
        ipv4_address: 172.123.0.12
    volumes:
      - ../sample-conf/remote/site2:/home/smcql/sample-conf
    restart: unless-stopped
    command: sleep infinity

  smcql_broker:
    platform: linux/amd64
    container_name: smcql_broker
    image: smcql
    networks:
      smcql_bridge:
        ipv4_address: 172.123.0.10
    volumes:
      - ../sample-conf/remote/broker:/home/smcql/sample-conf
    restart: unless-stopped
    command: sleep infinity

networks:
  smcql_bridge:
    name: smcql_bridge
    driver: bridge
    ipam:
      config:
        - subnet: 172.123.0.1/24
